export const API_BASE_URL = 'http://localhost:60748';

export const ROLES = {
  ADMIN: 1,
  TRAINER: 2,
  MEMBER: 3,
};

export const ROLE_NAMES = {
  1: 'Admin',
  2: 'Trainer',
  3: 'Member',
};

export const ACTIONS = {
  // UI
  SHOW_TOAST: 'SHOW_TOAST',
  HIDE_TOAST: 'HIDE_TOAST',
  SET_CURRENT_USER_ID: 'SET_CURRENT_USER_ID',
  SET_THEME: 'SET_THEME',

  // Auth
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',

  // Users
  FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',

  // Members
  FETCH_MEMBERS_REQUEST: 'FETCH_MEMBERS_REQUEST',
  FETCH_MEMBERS_SUCCESS: 'FETCH_MEMBERS_SUCCESS',
  FETCH_MEMBERS_FAILURE: 'FETCH_MEMBERS_FAILURE',
  DELETE_MEMBER_SUCCESS: 'DELETE_MEMBER_SUCCESS',

  // Trainers
  FETCH_TRAINERS_REQUEST: 'FETCH_TRAINERS_REQUEST',
  FETCH_TRAINERS_SUCCESS: 'FETCH_TRAINERS_SUCCESS',
  FETCH_TRAINERS_FAILURE: 'FETCH_TRAINERS_FAILURE',

  // Plans
  FETCH_PLANS_REQUEST: 'FETCH_PLANS_REQUEST',
  FETCH_PLANS_SUCCESS: 'FETCH_PLANS_SUCCESS',
  FETCH_PLANS_FAILURE: 'FETCH_PLANS_FAILURE',

  // Subscriptions
  FETCH_SUBSCRIPTIONS_REQUEST: 'FETCH_SUBSCRIPTIONS_REQUEST',
  FETCH_SUBSCRIPTIONS_SUCCESS: 'FETCH_SUBSCRIPTIONS_SUCCESS',
  FETCH_SUBSCRIPTIONS_FAILURE: 'FETCH_SUBSCRIPTIONS_FAILURE',
  DELETE_SUBSCRIPTION_SUCCESS: 'DELETE_SUBSCRIPTION_SUCCESS',

  // Payments
  FETCH_PAYMENTS_REQUEST: 'FETCH_PAYMENTS_REQUEST',
  FETCH_PAYMENTS_SUCCESS: 'FETCH_PAYMENTS_SUCCESS',
  FETCH_PAYMENTS_FAILURE: 'FETCH_PAYMENTS_FAILURE',

  // Schedules
  FETCH_SCHEDULES_REQUEST: 'FETCH_SCHEDULES_REQUEST',
  FETCH_SCHEDULES_SUCCESS: 'FETCH_SCHEDULES_SUCCESS',
  FETCH_SCHEDULES_FAILURE: 'FETCH_SCHEDULES_FAILURE',

  // Timeslots
  FETCH_TIMESLOTS_REQUEST: 'FETCH_TIMESLOTS_REQUEST',
  FETCH_TIMESLOTS_SUCCESS: 'FETCH_TIMESLOTS_SUCCESS',
  FETCH_TIMESLOTS_FAILURE: 'FETCH_TIMESLOTS_FAILURE',

  // Trainer Timeslots
  FETCH_TRAINER_TIMESLOTS_REQUEST: 'FETCH_TRAINER_TIMESLOTS_REQUEST',
  FETCH_TRAINER_TIMESLOTS_SUCCESS: 'FETCH_TRAINER_TIMESLOTS_SUCCESS',
  FETCH_TRAINER_TIMESLOTS_FAILURE: 'FETCH_TRAINER_TIMESLOTS_FAILURE',

  // Assignments
  FETCH_ASSIGNMENTS_REQUEST: 'FETCH_ASSIGNMENTS_REQUEST',
  FETCH_ASSIGNMENTS_SUCCESS: 'FETCH_ASSIGNMENTS_SUCCESS',
  FETCH_ASSIGNMENTS_FAILURE: 'FETCH_ASSIGNMENTS_FAILURE',
  DELETE_ASSIGNMENT_SUCCESS: 'DELETE_ASSIGNMENT_SUCCESS',

  // Workouts (NonEquipmentExercise)
  FETCH_WORKOUTS_REQUEST: 'FETCH_WORKOUTS_REQUEST',
  FETCH_WORKOUTS_SUCCESS: 'FETCH_WORKOUTS_SUCCESS',
  FETCH_WORKOUTS_FAILURE: 'FETCH_WORKOUTS_FAILURE',

  // Exercises master
  FETCH_EXERCISES_REQUEST: 'FETCH_EXERCISES_REQUEST',
  FETCH_EXERCISES_SUCCESS: 'FETCH_EXERCISES_SUCCESS',
  FETCH_EXERCISES_FAILURE: 'FETCH_EXERCISES_FAILURE',

  // Attendance
  FETCH_ATTENDANCE_REQUEST: 'FETCH_ATTENDANCE_REQUEST',
  FETCH_ATTENDANCE_SUCCESS: 'FETCH_ATTENDANCE_SUCCESS',
  FETCH_ATTENDANCE_FAILURE: 'FETCH_ATTENDANCE_FAILURE',

  // Equipment
  FETCH_EQUIPMENT_REQUEST: 'FETCH_EQUIPMENT_REQUEST',
  FETCH_EQUIPMENT_SUCCESS: 'FETCH_EQUIPMENT_SUCCESS',
  FETCH_EQUIPMENT_FAILURE: 'FETCH_EQUIPMENT_FAILURE',

  // Equipment Usage (live)
  FETCH_EQUIPMENT_USAGE_REQUEST: 'FETCH_EQUIPMENT_USAGE_REQUEST',
  FETCH_EQUIPMENT_USAGE_SUCCESS: 'FETCH_EQUIPMENT_USAGE_SUCCESS',
  FETCH_EQUIPMENT_USAGE_FAILURE: 'FETCH_EQUIPMENT_USAGE_FAILURE',
};
